# Container for making AppImage and Windows builds
FROM rust:1.92

# Build deps
# See https://wiki.libsdl.org/SDL3/README-linux#build-dependencies
RUN apt-get update && apt-get install -y gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 cmake zip \
	libpulse-dev libxcursor-dev libxi-dev libxrandr-dev libxss-dev libxtst-dev libxkbcommon-dev \
	libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev libudev-dev \
	libwayland-dev

# Windows cross compiler
RUN rustup target add x86_64-pc-windows-gnu

# AppImage build tool
RUN wget -O /usr/local/bin/linuxdeploy https://github.com/linuxdeploy/linuxdeploy/releases/download/1-alpha-20251107-1/linuxdeploy-x86_64.AppImage ; chmod a+x /usr/local/bin/linuxdeploy
RUN wget -O /usr/local/bin/appimage-runtime https://github.com/AppImage/type2-runtime/releases/download/continuous/runtime-x86_64

# Build directory
RUN mkdir /target ; chmod a+rwx /target

# Dummy main.rs so we can run cargo fetch
WORKDIR /app
ADD pkg/main.rs /app/src/main.rs

# Cache Rust deps
# We still need to build these every time
# but we can at least save some bandwidth.
ADD Cargo.lock Cargo.toml /app/
RUN cargo fetch

